#! /bin/sh
#
#
# Dual monitor setup
#
if [ -x /home/andre/bin/DualMonitorSetUp.sh ];then
	bash /home/andre/bin/DualMonitorSetUp.sh
fi

pgrep -x sxhkd > /dev/null || sxhkd &
polybar monitor1 &
polybar monitor2 &
polybar monitor3 &

bspc monitor eDP-1 -d  1 2 3 4 5
bspc monitor DVI-I-1-1 -d  4 5 6 
bspc monitor DVI-I-2-2 -d  7 8 9 
# bspc monitor HDMI-2 -d 4 5 6

#
# Configs
#
bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# 
# Rules
#
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# 
# Wallpaper and cursor set
#
hsetroot -fill $HOME/Downloads/Hashira_DemonSlayer.jpg
xsetroot -cursor_name left_ptr &

# 
# Set up pywal theme
# 
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

#
# Startup applications
#
# Startup transparency 
picom -b --config $HOME/.config/picom-ibhagwan-git/src/picom/picom.conf &

firefox &

# If there is already a session running, attach to it.
if [[ $(tmux ls) ]]; then
	alacritty -e bash -c "tmux attach" &
else
	alacritty -e bash -c "tmux" &
fi

obsidian &

if [ -f $HOME/bin/update_obsidian_theme.sh ]; then
	. $HOME/bin/update_obsidian_theme.sh 
fi

# Apply pywal theme to rest of system
sleep 1 && . "${HOME}/.config/pywal/walstart.sh"
