#! /bin/sh
#
#
# Variables
# Attribute random value to background. Will change everytime system boots up.
RAND=$((1+$RANDOM%3))
if [[ $RAND == 1 ]]
then
	export BACKGROUND=$HOME/Pictures/AttackOnTitan.jpg
elif [[ $RAND == 2 ]]
then
	export BACKGROUND=$HOME/Pictures/Hashira_DemonSlayer.jpg
elif [[ $RAND == 3 ]]
then
	export BACKGROUND=$HOME/Pictures/space-man.jpg
fi


# Dual monitor setup
#
if [ -x /home/andre/bin/DualMonitorSetUp.sh ]
then
	bash /home/andre/bin/DualMonitorSetUp.sh DVI-I-1-1 DVI-I-2-2

	if [[ ! $(xrandr | grep "DVI.*disconnected") ]]
	then
		# Set default apps startup screens
		bspc rule -a firefox desktop="^1"
		bspc rule -a Alacritty desktop="^4"
		bspc rule -a obsidian desktop="^7"

	else
		bspc rule -a firefox desktop="^1"
		bspc rule -a Alacritty desktop="^2"
		bspc rule -a obsidian desktop="^3"
	fi
fi

pgrep -x sxhkd > /dev/null || sxhkd &

# Add monitors
bspc monitor eDP-1 -d  1 2 3 4 5
bspc monitor DVI-I-1-1 -d  6 7 8
bspc monitor DVI-I-2-2 -d  9 10 11 


# Was causing CPU issues. Not killing old instances..
killall polybar
polybar monitor1 &
polybar monitor2 &
polybar monitor3 &


#
# Configs
#
bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# 
# Rules
#
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# 
# Wallpaper and cursor set
#
hsetroot -fill $BACKGROUND
xsetroot -cursor_name left_ptr &

# 
# Set up pywal theme
# 
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

#
# Startup applications
#

# Startup firefox
if [[ -f $HOME/bin/firefox_startup.sh ]]
then
	. "${HOME}/bin/firefox_startup.sh"
fi

# Startup alacritty
# Kill sessions before starting
killall alacritty
alacritty &

# Apply pywal theme to rest of system
# Wait a bit for changes to apply to polybar
sleep 1 

if [[ -f $HOME/.config/pywal/walstart.sh ]]
then
	. "${HOME}/.config/pywal/walstart.sh"
fi

# Startup obisidan notes
killall electron
obsidian &

# Update obsidian pywal theme
if [[ -f $HOME/bin/update_obsidian_theme.sh ]]
then 
	$HOME/bin/update_obsidian_theme.sh
fi


# Remove rules that were setup on startup. Don't want these rules to apply after startup.
# Wait again a bit before removing these rules
sleep 15

bspc rule -r firefox
bspc rule -r Alacritty
bspc rule -r obsidian


# Startup transparency 
# 
# picom -b --config $HOME/.config/picom-ibhagwan-git/src/picom/picom.conf &

