#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar monitor1 &
polybar monitor2 &

bspc monitor eDP-1 -d  1 2 3 
bspc monitor HDMI-2 -d 4 5 6


#
# Configs
#
bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# 
# Rules
#
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# Dual monitor setup
#
if [ -x $HOME/bin/DualMonitorSetUp.sh ];then
	exec DualMonitorSetUp.sh
fi

# Wallpaper and cursor set
hsetroot -fill $HOME/Pictures/AttackOnTitan.jpg
xsetroot -cursor_name left_ptr &

#
# Startup applications
#
picom -b --config $HOME/.config/picom-ibhagwan-git/src/picom/picom.conf --experimental-backends &
firefox &

